#!/bin/bash

function minutes { echo "$(( 60 * $1 ))"; }
function hours { echo "$(( 60 * $(minutes $1) ))"; }

DATADIR="$(dirname "$(readlink -e "$0")")/data"
mkdir -p "$DATADIR"
INTERVAL="$(minutes 5)"
FILE_NAME_FORMAT='+%Y-%m-%d_%A'
RECORD_FORMAT='+%H:%M:%S'
TARGET_TIME="$(hours 4)"

file_name() { echo "$DATADIR/$(date "$FILE_NAME_FORMAT").txt"; }
time_worked() { tail -n +2 "$(file_name)" | awk 'BEGIN{ sum=0 }; { sum+=$1 }; END{ print sum }'; }
wish() { FILE="$(file_name)" ; [ -e "$FILE" ] && head -n 1 "$FILE"; }
time_formated() { date "$RECORD_FORMAT"; }
last_worked_at(){ tail -n 1 $(file_name) | awk '{print $2}'; }
unix_seconds() { date --date "$1" '+%s'; }
not_working(){ echo "$(( $(date '+%s') - $(unix_seconds "$(last_worked_at)") ))"; }
to_minutes() { echo $(( $1 / 60.0 )) }

target_file()
{
  FILE="$(file_name)"
  if [ ! -e "$FILE" ]; then
    WISH=""
    while [ -z "$WISH" ]; do
      WISH="$(zenity  --text "Желание на сегодня:" --entry)"
    done
    echo "$WISH" >> "$FILE"
  fi
  echo "$FILE"
}

record()
{
  while true; do
    sleep "$INTERVAL"
    FILE="$(target_file)"
    if zenity  --question --text "Работаешь?"; then
      echo "${INTERVAL} $(time_formated)"  >> "$FILE"
      notify-send "Умничка!:)"
      # there is no need to log negative cases
    fi
    if [ $(to_minutes $(not_working)) -gt 30 ];then
      notify-send "Ты уже полчаса ничего не делаешь -_-'"
    fi
  done
}


status()
{
  if [ -e "$(file_name)" ]; then
    if [ $(time_worked) -gt "$TARGET_TIME" ]; then
      echo "Ты всё на сегодня сделал! Можешь $(wish):)"
    else
      echo "Ещё нет. Поделай что-нибудь ещё."
    fi
  else
    echo "Нет информации за сегодня."
  fi
}

$@
